config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#top"
#  get "/users/sign_out", to: 'home#top'


  devise_scope :user do
    # write all your routes inside this block
    get "/users/sign_in", to: "sessions#new"
    get "users/sign_out", to: "devise/sessions#destroy"
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    home_top_path
  end

  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index 
    @posts = Post.all
  end

  def show 
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :author_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<% if user_signed_in? %>
  <%= current_user.email %>
  <%= session[:user_id]%>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" }%>
<% else %>
 <%= link_to "Log in", new_user_session_path, data: { turbo: "false" }  %>
<% end %>

<%= link_to "Posts", posts_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post %>
    </li>
  <% end %>
</ul>

<%= link_to "New Post", new_post_path%>

<%= link_to "Home", root_path%>

app/views/posts/new.html.erb
<div>New Post</div>

<div data-turbo="false">
  <%= form_with model: Post do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% @post.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% @post.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <%= @post.errors.messages %>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div>
      <%= form.submit "Submit" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<%= @post.user.name %>

<%= link_to "Back", posts_path%>